backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: "Projects"
    preview: false
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Date, name: date, widget: "date"}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}
  - name: "Conti"
    preview: false
    label: "Conti"
    folder: "content/conti"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {label: Date, name: date, widget: "date"}
      - {label: Image, name: image, widget: image}
      - {label: Body, name: body, widget: markdown}      
      
      
      